name: Haskell CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc_version: [8.6.5, 8.8.1]
    name: Haskell GHC ${{ matrix.ghc_version }} build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc_version }}
        cabal-version: '3.0'
    - name: Install dependencies
      run: |
        cabal update
        cabal install --only-dependencies
    - name: Build
      run: |
        cabal configure
        cabal build
