name: Build only

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: GHC ${{ matrix.name }}
    env:
      CABAL_REINIT_CONFIG: y
      LC_ALL: C.UTF-8

      ENABLE_INSTALL: "n"

      STACK_UPGRADE: "y"

      CABAL_CHECK_RELAX: y
      CABAL_NO_SANDBOX: y
      CABAL_HACKAGE_MIRROR: hackage.haskell.org:http://hackage.fpcomplete.com

      PACKCHECK: "./packcheck.sh"
      PACKCHECK_GITHUB_URL: "https://raw.githubusercontent.com/composewell/packcheck"
      PACKCHECK_GITHUB_COMMIT: "ccc55fd4b895e842ca6e2d8ac63aa4acc1c3209a"

      BUILD: ${{ matrix.build }}
      GHCVER: ${{ matrix.ghc_version }}
      CABALVER: ${{ matrix.cabal_version }}
      CABAL_PROJECT: ${{ matrix.cabal_project }}
      CABAL_BUILD_OPTIONS: ${{ matrix.cabal_build_options }}
      DISABLE_SDIST_BUILD: ${{ matrix.disable_sdist_build }}
      GHCUP_GHC_OPTIONS: ${{ matrix.ghcup_ghc_options }}
      GHCUP_VERSION: 0.1.20.0

    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        name: [head, 9.12.1, 9.10.1, 9.8.1, 9.6.3, 9.4.7, 9.2.8+macOS, 9.0.2, 8.10.7, 8.8.4, 8.6.5]
        cabal_version: ["3.8.1.0"]
        include:
          - name: head
            ghc_version: head
            build: cabal-v2
            runner: ubuntu-latest
            cabal_project: cabal.project.ghc-head
            ghcup_ghc_options: "-u https://gitlab.haskell.org/ghc/ghc/-/jobs/artifacts/master/raw/ghc-x86_64-linux-deb10-int_native-validate.tar.xz?job=x86_64-linux-deb10-int_native-validate"
          - name: 9.12.1
            ghc_version: 9.12.1
            build: cabal-v2
            runner: ubuntu-latest
          - name: 9.10.1
            ghc_version: 9.10.1
            build: cabal-v2
            runner: ubuntu-latest
          - name: 9.8.1
            ghc_version: 9.8.1
            build: cabal-v2
            runner: ubuntu-latest
          - name: 9.6.3
            ghc_version: 9.6.3
            build: cabal-v2
            runner: ubuntu-latest
          - name: 9.4.7
            ghc_version: 9.4.7
            build: cabal-v2
            runner: ubuntu-latest
          - name: 9.2.8+macOS
            ghc_version: 9.2.8
            build: cabal-v2
            runner: macos-latest
            disable_sdist_build: "y"
          - name: 9.0.2
            ghc_version: 9.0.2
            build: cabal-v2
            runner: ubuntu-latest
          # macos build on ghc 8.10.7 fails with some LLVM version issues.
          # See: https://github.com/haskell/vscode-haskell/issues/667
          - name: 8.10.7
            ghc_version: 8.10.7
            build: cabal-v2
            runner: ubuntu-latest
          - name: 8.8.4
            ghc_version: 8.8.4
            build: cabal-v2
            runner: ubuntu-latest
          - name: 8.6.5
            ghc_version: 8.6.5
            build: cabal-v2
            runner: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      name: Cache ~/.cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-${{ matrix.ghc_version }}-cabal

    - name: Download packcheck
      run: |
        if test ! -e "$PACKCHECK"
        then
          if test -z "$PACKCHECK_GITHUB_COMMIT"
          then
              die "PACKCHECK_GITHUB_COMMIT is not specified."
          fi
          PACKCHECK_URL=${PACKCHECK_GITHUB_URL}/${PACKCHECK_GITHUB_COMMIT}/packcheck.sh
          curl --fail -sL -o "$PACKCHECK" $PACKCHECK_URL || exit 1
          chmod +x $PACKCHECK
        elif test ! -x "$PACKCHECK"
        then
            chmod +x $PACKCHECK
        fi

    - name: Run packcheck
      run: |
        bash -c "$PACKCHECK $BUILD"
